### ISSUE TITLE
This more of an idea than issue ... SQL

### ISSUE THREAD

**Issue by aktxyz** [moov-io/ach-test-harness#22]
Ever consider a SQL like matcher?

select * from entries where sec='' and amount > 100

or something like that?

**Comment by adamdecaf** [comment]
Hey @aktxyz thanks for the idea. I did think about a SQL syntax for matching these, but then we'd need to write/import a SQL parser with a custom grammar.  It would also require teaching non-engineering folks how to write SQL. YAML was a lot easier to get started.

Appreciate the suggestion and if you have more questions or feedback let us know!

**Comment by aktxyz** [comment]
I had just read somewhere about a company that took unstructured data and stuff into a in memory sql lite ... just so they could run nice queries against it ... and for some reason I thought ACH !

adding a sqlite dependency I am sure is a not starter ... and the few sql'ish go things out there are probably not ready

anyhoo thanks for commenting

**Comment by adamdecaf** [comment]
I can totally see an ACH warehousing project that allows you to run SQL-like queries across millions of indexed files. That would be really useful!
